flake:

{ config, lib, pkgs, ... }:

let
  cfg = config.services.devpush;
  inherit (lib) mkEnableOption mkOption mkIf types optionalString;

  # Build the compose command arguments
  composeFiles = [
    "${cfg.package}/compose/base.yml"
    "${cfg.package}/compose/override.yml"
    "${cfg.package}/compose/ssl-${cfg.settings.certChallengeProvider}.yml"
  ];

  composeFileArgs = lib.concatMapStringsSep " " (f: "-f ${f}") composeFiles;

  # Script to generate secrets if they don't exist
  generateSecretsScript = pkgs.writeShellScript "devpush-generate-secrets" ''
    set -euo pipefail

    SECRETS_FILE="${cfg.dataDir}/.secrets"

    if [[ ! -f "$SECRETS_FILE" ]]; then
      echo "Generating DevPush secrets..."
      SECRET_KEY=$(${pkgs.openssl}/bin/openssl rand -hex 32)
      ENCRYPTION_KEY=$(${pkgs.openssl}/bin/openssl rand -base64 32 | tr '+/' '-_')
      POSTGRES_PASSWORD=$(${pkgs.openssl}/bin/openssl rand -hex 32)

      cat > "$SECRETS_FILE" <<EOF
SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
EOF
      chmod 600 "$SECRETS_FILE"
      chown ${cfg.user}:${cfg.group} "$SECRETS_FILE"
    fi
  '';

  # Script to build the combined .env file
  buildEnvScript = pkgs.writeShellScript "devpush-build-env" ''
    set -euo pipefail

    ENV_FILE="${cfg.dataDir}/.env"
    SECRETS_FILE="${cfg.dataDir}/.secrets"
    USER_SECRETS="${cfg.secretsFile}"

    # Get UID/GID
    SERVICE_UID=$(${pkgs.coreutils}/bin/id -u ${cfg.user})
    SERVICE_GID=$(${pkgs.coreutils}/bin/id -g ${cfg.user})

    # Detect server IP if not specified
    SERVER_IP="${optionalString (cfg.settings.serverIp != null) cfg.settings.serverIp}"
    if [[ -z "$SERVER_IP" ]]; then
      SERVER_IP=$(${pkgs.curl}/bin/curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || \
                  ${pkgs.curl}/bin/curl -fsS --max-time 5 http://checkip.amazonaws.com 2>/dev/null || \
                  ${pkgs.iproute2}/bin/ip route get 1 2>/dev/null | ${pkgs.gawk}/bin/awk '{print $7; exit}' || \
                  echo "127.0.0.1")
    fi

    # Build the .env file
    # Note: DATA_DIR, APP_DIR, LOG_DIR are intentionally NOT included here.
    # These are host paths used by docker-compose for volume mounts (passed via
    # shell environment). The app container uses its defaults (/data, /app).
    cat > "$ENV_FILE" <<'ENVEOF'
# DevPush Configuration
# Generated by NixOS module - do not edit directly

# Service user
ENVEOF
    cat >> "$ENV_FILE" <<ENVEOF
SERVICE_UID=$SERVICE_UID
SERVICE_GID=$SERVICE_GID

# Network
SERVER_IP=$SERVER_IP

# Application settings
APP_HOSTNAME=${cfg.settings.appHostname}
DEPLOY_DOMAIN=${cfg.settings.deployDomain}
LE_EMAIL=${cfg.settings.letsEncryptEmail}
CERT_CHALLENGE_PROVIDER=${cfg.settings.certChallengeProvider}

# Database
POSTGRES_DB=devpush
POSTGRES_USER=devpush-app
ENVEOF

    # Append auto-generated secrets
    if [[ -f "$SECRETS_FILE" ]]; then
      echo "" >> "$ENV_FILE"
      echo "# Auto-generated secrets" >> "$ENV_FILE"
      cat "$SECRETS_FILE" >> "$ENV_FILE"
    fi

    # Append user secrets
    if [[ -f "$USER_SECRETS" ]]; then
      echo "" >> "$ENV_FILE"
      echo "# User-provided secrets" >> "$ENV_FILE"
      cat "$USER_SECRETS" >> "$ENV_FILE"
    fi

    chmod 600 "$ENV_FILE"
    chown ${cfg.user}:${cfg.group} "$ENV_FILE"
  '';

  # Script to build runner images
  buildRunnersScript = pkgs.writeShellScript "devpush-build-runners" ''
    set -euo pipefail

    IMAGES_JSON="${cfg.package}/app/settings/images.json"
    RUNNER_DIR="${cfg.package}/docker/runner"

    if [[ ! -f "$IMAGES_JSON" ]]; then
      echo "No images.json found, skipping runner builds"
      exit 0
    fi

    ${pkgs.jq}/bin/jq -r '.[] | select(type=="object") | select(.slug and (.slug|type=="string")) | .slug' "$IMAGES_JSON" 2>/dev/null | while read -r slug; do
      [[ -n "$slug" ]] || continue

      DOCKERFILE="$RUNNER_DIR/Dockerfile.$slug"
      if [[ -f "$DOCKERFILE" ]]; then
        echo "Building runner image: $slug"
        ${pkgs.docker}/bin/docker build -f "$DOCKERFILE" -t "runner-$slug" "$RUNNER_DIR"
      else
        echo "Skipping $slug (no Dockerfile.$slug found)"
      fi
    done
  '';

  # Script to run database migrations
  migrateScript = pkgs.writeShellScript "devpush-migrate" ''
    set -euo pipefail

    # Wait for app container to be ready
    for i in $(seq 1 30); do
      CONTAINER=$(${pkgs.docker}/bin/docker ps --filter "label=com.docker.compose.project=devpush" --filter "label=com.docker.compose.service=app" -q | head -1 || true)
      if [[ -n "$CONTAINER" ]]; then
        STATUS=$(${pkgs.docker}/bin/docker inspect --format '{{.State.Status}}' "$CONTAINER" 2>/dev/null || true)
        if [[ "$STATUS" == "running" ]]; then
          break
        fi
      fi
      sleep 2
    done

    if [[ -z "''${CONTAINER:-}" ]]; then
      echo "App container not found, skipping migrations"
      exit 0
    fi

    echo "Running database migrations..."
    ${pkgs.docker}/bin/docker exec "$CONTAINER" uv run alembic upgrade head || true
  '';

in {
  options.services.devpush = {
    enable = mkEnableOption "DevPush deployment platform";

    package = mkOption {
      type = types.path;
      default = flake;
      defaultText = "flake source";
      description = "DevPush source package";
    };

    dataDir = mkOption {
      type = types.path;
      default = "/var/lib/devpush";
      description = "Directory for DevPush data";
    };

    logDir = mkOption {
      type = types.path;
      default = "/var/log/devpush";
      description = "Directory for DevPush logs";
    };

    user = mkOption {
      type = types.str;
      default = "devpush";
      description = "User account under which DevPush runs";
    };

    group = mkOption {
      type = types.str;
      default = "devpush";
      description = "Group under which DevPush runs";
    };

    settings = {
      appHostname = mkOption {
        type = types.str;
        description = "Hostname for the DevPush web interface (e.g., devpush.example.com)";
        example = "devpush.example.com";
      };

      deployDomain = mkOption {
        type = types.str;
        description = "Base domain for deployments (e.g., deploy.example.com)";
        example = "deploy.example.com";
      };

      letsEncryptEmail = mkOption {
        type = types.str;
        description = "Email address for Let's Encrypt certificate notifications";
        example = "admin@example.com";
      };

      serverIp = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Public IP address of the server. Auto-detected if null.";
        example = "203.0.113.10";
      };

      certChallengeProvider = mkOption {
        type = types.enum [ "default" "cloudflare" "route53" "gcloud" "digitalocean" "azure" ];
        default = "default";
        description = ''
          Certificate challenge provider for Let's Encrypt.
          - default: HTTP-01 challenge
          - cloudflare/route53/gcloud/digitalocean/azure: DNS-01 challenge

          For DNS providers, you must include the required environment variables
          in your secretsFile.
        '';
      };
    };

    secretsFile = mkOption {
      type = types.path;
      description = ''
        Path to a file containing secrets as environment variables.
        Must include:
        - GITHUB_APP_ID, GITHUB_APP_NAME, GITHUB_APP_PRIVATE_KEY
        - GITHUB_APP_WEBHOOK_SECRET, GITHUB_APP_CLIENT_ID, GITHUB_APP_CLIENT_SECRET
        - EMAIL_SENDER_ADDRESS, RESEND_API_KEY

        For DNS challenge providers, also include the provider-specific variables:
        - cloudflare: CF_DNS_API_TOKEN
        - route53: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
        - gcloud: GCE_PROJECT (and place gcloud-sa.json in dataDir)
        - digitalocean: DO_AUTH_TOKEN
        - azure: AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID,
                 AZURE_TENANT_ID, AZURE_RESOURCE_GROUP
      '';
      example = "/run/secrets/devpush.env";
    };
  };

  config = mkIf cfg.enable {
    # Enable Docker
    virtualisation.docker.enable = true;

    # Create user and group
    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.group;
      home = cfg.dataDir;
      extraGroups = [ "docker" ];
      description = "DevPush service user";
    };

    users.groups.${cfg.group} = {};

    # Create directories
    systemd.tmpfiles.rules = [
      "d ${cfg.dataDir} 0750 ${cfg.user} ${cfg.group} -"
      "d ${cfg.dataDir}/traefik 0750 ${cfg.user} ${cfg.group} -"
      "d ${cfg.dataDir}/upload 0750 ${cfg.user} ${cfg.group} -"
      "d ${cfg.logDir} 0750 ${cfg.user} ${cfg.group} -"
    ];

    # Setup service (runs before main service)
    systemd.services.devpush-setup = {
      description = "DevPush setup (secrets, runners, env)";
      wantedBy = [ "multi-user.target" ];
      before = [ "devpush.service" ];
      after = [ "docker.service" "network-online.target" ];
      wants = [ "docker.service" "network-online.target" ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = pkgs.writeShellScript "devpush-setup-exec" ''
          set -euo pipefail

          echo "Generating secrets..."
          ${generateSecretsScript}

          echo "Building environment file..."
          ${buildEnvScript}

          echo "Ensuring acme.json exists..."
          touch ${cfg.dataDir}/traefik/acme.json
          chmod 600 ${cfg.dataDir}/traefik/acme.json
          chown ${cfg.user}:${cfg.group} ${cfg.dataDir}/traefik/acme.json

          echo "Building runner images..."
          ${buildRunnersScript}

          echo "DevPush setup complete."
        '';
      };
    };

    # Main service
    systemd.services.devpush = {
      description = "DevPush deployment platform";
      wantedBy = [ "multi-user.target" ];
      after = [ "devpush-setup.service" "docker.service" "network-online.target" ];
      wants = [ "docker.service" "network-online.target" ];
      requires = [ "devpush-setup.service" ];

      environment = {
        COMPOSE_PROJECT_NAME = "devpush";
        # Host paths for docker-compose volume mounts
        DATA_DIR = cfg.dataDir;
        APP_DIR = cfg.package;
        LOG_DIR = cfg.logDir;
      };

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        TimeoutStartSec = 600;
        TimeoutStopSec = 600;

        ExecStart = pkgs.writeShellScript "devpush-start" ''
          set -euo pipefail

          echo "Starting DevPush..."
          ${pkgs.docker}/bin/docker compose \
            -p devpush \
            --env-file ${cfg.dataDir}/.env \
            ${composeFileArgs} \
            up -d --remove-orphans

          # Wait for app to be ready
          echo "Waiting for app container..."
          for i in $(seq 1 60); do
            CONTAINER=$(${pkgs.docker}/bin/docker ps --filter "label=com.docker.compose.project=devpush" --filter "label=com.docker.compose.service=app" -q | head -1 || true)
            if [[ -n "$CONTAINER" ]]; then
              STATUS=$(${pkgs.docker}/bin/docker inspect --format '{{.State.Status}}{{if .State.Health}}:{{.State.Health.Status}}{{end}}' "$CONTAINER" 2>/dev/null || true)
              case "$STATUS" in
                running:healthy|running)
                  echo "App container is ready."
                  break
                  ;;
              esac
            fi
            sleep 2
          done

          # Run migrations
          ${migrateScript}

          echo "DevPush started successfully."
        '';

        ExecStop = pkgs.writeShellScript "devpush-stop" ''
          set -euo pipefail

          echo "Stopping DevPush..."
          ${pkgs.docker}/bin/docker compose \
            -p devpush \
            --env-file ${cfg.dataDir}/.env \
            ${composeFileArgs} \
            stop

          echo "DevPush stopped."
        '';
      };
    };

    # Open firewall ports for HTTP/HTTPS
    networking.firewall.allowedTCPPorts = [ 80 443 ];
  };
}
